# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "builds/virtualbox-centos7_virtualbox.box"
  config.ssh.username = "root"
  config.ssh.password = "password"
end
